apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: backend-feed
  name: backend-feed
spec:
  selector:
    matchLabels:
      service: backend-feed
  replicas: 1
  template:
    metadata:
      labels:
        service: backend-feed
    spec:
      containers:
      - image: lmarquesmoreira/udacity-restapi-feed
        name: backend-feed
        imagePullPolicy: Always  
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "1024Mi"
            cpu: "500m"                  
        env:
        - name: URL
          valueFrom:
            configMapKeyRef:
              name: env-config
              key: URL
        - name: UDAGRAM_AWS_MEDIA_BUCKET
          valueFrom:
            configMapKeyRef:
              name: env-config
              key: UDAGRAM_AWS_MEDIA_BUCKET
        - name: UDAGRAM_AWS_PROFILE
          valueFrom:
            configMapKeyRef:
              name: env-config
              key: UDAGRAM_AWS_PROFILE
        - name: UDAGRAM_AWS_REGION
          valueFrom:
            configMapKeyRef:
              name: env-config
              key: UDAGRAM_AWS_REGION
        - name: JWT_SECRET
          valueFrom:
            configMapKeyRef:
              name: env-config
              key: JWT_SECRET
        - name: UDAGRAM_DATABASE_DATABASE
          valueFrom:
            configMapKeyRef:
              name: env-config
              key: UDAGRAM_DATABASE_DATABASE
        - name: UDAGRAM_DATABASE_HOST
          valueFrom:
            configMapKeyRef:
              name: env-config
              key: UDAGRAM_DATABASE_HOST
        - name: UDAGRAM_DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: env-secret
              key: UDAGRAM_DATABASE_PASSWORD
        - name: UDAGRAM_DATABASE_USERNAME
          valueFrom:
            secretKeyRef:
              name: env-secret
              key: UDAGRAM_DATABASE_USERNAME      
        - name: UDAGRAM_DATABASE_DIALECT
          valueFrom:
            configMapKeyRef:
              name: env-config
              key: UDAGRAM_DATABASE_DIALECT  
        volumeMounts:
        - name: aws-secret
          mountPath: "/root/.aws/"
          readOnly: true        
      restartPolicy: Always
      volumes:
      - name: aws-secret
        secret:
          secretName: aws-secret       